version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=passwrd123
      - DATABASE_NAME=apipython
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=8c6740ebff5060ef68ea6fcb565cb940a0583b1904fb175394e878292991f1cd
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passwrd123
      - POSTGRES_DB=apipython

    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: